name: Build & test

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  
  CodeChecker:
    runs-on: [ubuntu-20.04]
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v2

      # Prepare a build
      - name: "Prepare build"
        run: |
          mkdir -pv Build
          cd Build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..

      # Run the analysis
      - uses: whisperity/codechecker-analysis-action@v1
        id: codechecker
        with:
          logfile: ${{ github.workspace }}/Build/compile_commands.json
          config: ${{ github.workspace }}/.codechecker.yml

      # Upload the results to the CI.
      - uses: actions/upload-artifact@v2
        with:
          name: "CodeChecker Bug Reports"
          path: ${{ steps.codechecker.outputs.result-html-dir }}

      # Break the build if there are *ANY* warnings emitted by the analysers.
      - name: "Break build if CodeChecker reported any findings"
        if: ${{ steps.codechecker.outputs.warnings == 'true' }}
        run: exit 1